package com.doubtnutapp.widgetmanager

object WidgetTypes {

    const val TYPE_COURSE_LIST = "faculty_course_list"
    const val TYPE_STRUCTURED_COURSE_LIST = "structured_course"
    const val TYPE_FILTER_TABS = "filter_tabs"
    const val TYPE_HEADER_MESSAGE = "header_message"
    const val TYPE_BANNER_IMAGE = "banner_image"
    const val TYPE_PAYMENT_CARD = "payment_card"
    const val TYPE_FACULTY_GRID = "faculty_grid"
    const val TYPE_VERTICAL_LIST = "vertical_list"
    const val TYPE_TOPPERS_SPEAK = "TOPPERS_SPEAK"
    const val TYPE_BUTTON = "button"

    const val TYPE_HORIZONTAL_LIST = "horizontal_list"
    const val TYPE_VERTICAL_LIST_2 = "vertical_list_2"
    const val TYPE_CAROUSEL_LIST = "carousel_list"
    const val TYPE_TAB_LIST = "tab_list"
    const val TYPE_WHATSAPP = "whatsapp"
    const val TYPE_DAILY_QUIZ = "daily_quiz"

    const val WIDGET_TYPE_FEED_POST = "feed_post"
    const val WIDGET_TYPE_RECENT_STATUS = "widget_recent_status"

    const val TYPE_COURSE_TAB = "course_tabs"
    const val TYPE_COURSE_LIST_FILTER = "course_list_filter"
    const val TYPE_REMINDER_CARD = "reminder_card"
    const val TYPE_SIMPLE_TEXT = "simple_text"
    const val TYPE_ALL_COURSE_LIST = "course_list"
    const val TYPE_COURSE_FILTER_EXAM = "course_filter_exam"
    const val TYPE_COURSE_FILTER_SUBJECT = "subject_filters"
    const val TYPE_NOTES_LIST = "resource_notes"
    const val TYPE_BOOKMARK_LIST = "bookmark_list"
    const val TYPE_PURCHASED_CLASSES = "vip-content"
    const val TYPE_LIVE_CLASS_CATEGORY = "course_category_carousel"
    const val TYPE_PAYMENT_HISTORY = "purchase_history"
    const val TYPE_COURSE = "widget_course_v1"
    const val TYPE_COURSE_V2 = "widget_course_v2"
    const val TYPE_COURSE_PROGRESS = "progress_bar"
    const val TYPE_RELATED_LECTURES_WIDGET = "related_lecture"
    const val TYPE_NOTIFY_LIVE_CLASS_WIDGET = "resource_page_notify"
    const val TYPE_RESOURCE_PAGE_UPCOMING_WIDGET = "resource_page_upcoming"
    const val TYPE_COURSE_UPCOMING_LECTURES_WIDGET = "course_page_carousel"
    const val TYPE_COURSE_INFO_WIDGET = "course_info"
    const val TYPE_TOPICS_COVERED_WIDGET = "topic_list"
    const val TYPE_ALL_TOPICS_WIDGET = "course_topics"
    const val TYPE_LIVE_CLASSES_INFO = "description_card"
    const val TYPE_RANKERS_CLASSES = "info"
    const val TYPE_RANKERS = "rankers"

    const val TYPE_WIDGET_IMAGE_TEXT = "widget_image_text"

    const val TYPE_RESOURCE_V4 = "resource_v4"
    const val TYPE_RESOURCE_NOTES_V3 = "resource_notes_v3"

    const val TYPE_COURSE_CONTENT = "course_content"
    const val TYPE_COURSE_EXAM_TABS = "course_exam_tabs"
    const val TYPE_COURSE_TYPE_TABS = "course_type_filter"
    const val TYPE_COURSE_CLASS_TABS = "class_filters"
    const val TYPE_COURSE_PAYMENT_CARD_LIST = "payment_card_list"
    const val TYPE_PROMO_LIST = "promo_list"
    const val TYPE_PLAN_TAB = "plan_filters"
    const val TYPE_PLAN_INFO = "package_info"
    const val TYPE_PLAN_LIST = "package_list"
    const val TYPE_MY_PLAN = "my_plan"
    const val TYPE_COURSE_TYPE_FILTER = "course_type_filters"
    const val TYPE_LIVE_CLASS_CAROUSEL = "live_class_carousel"

    const val TYPE_COURSE_COMMON = "course_list2"
    const val TYPE_SYLLABUS2 = "course_syllabus"
    const val TYPE_TIME_TABLE = "timetable_list"
    const val TYPE_SCHEDULE = "schedule"
    const val TYPE_SCHEDULE_HEADER = "schedule_header"
    const val TYPE_SCHEDULE_NO_DATA = "schedule_no_data"
    const val TYPE_ICON_HEADER = "icon_header"
    const val TYPE_PLAN_DESCRIPTION = "plan_info"
    const val TYPE_PACKAGE_DETAIL = "package_details"
    const val TYPE_PACKAGE_DETAIL_V2 = "package_details_v2"
    const val TYPE_COURSE_CATEGORY = "course_category"
    const val TYPE_WIDGET_PARENT = "widget_parent"
    const val TYPE_WIDGET_PARENT_TAB = "widget_parent_tab"
    const val TYPE_WIDGET_IPL_SCORE_BOARD = "widget_ipl_scoreboard"
    const val TYPE_COURSE_CHILD = "widget_course"
    const val TYPE_COURSE_CHILD_CAROUSEL = "widget_course_carousel"
    const val TYPE_COURSE_CHILD_RESOURCE = "widget_course_resource"
    const val TYPE_FACULTY_GRID2 = "faculty_grid2"
    const val TYPE_COURSE_SUBJECT = "course_subject"
    const val TYPE_LIVE_CLASS_CAROUSEL_CARD = "live_class_carousel_card"
    const val TYPE_LIVE_CLASS_CAROUSEL_CARD_2 = "live_class_carousel_card_2"
    const val TYPE_SALE_WIDGET = "nudges"
    const val TYPE_ACTIVATE_TRIAL_WIDGET = "activate_trial_widget"
    const val TYPE_NOTES_FILTER = "notes_filter"
    const val TYPE_CATEGORY_PAGE_FILTER = "category_filters"
    const val TYPE_CATEGORY_PAGE_FILTER_V2 = "category_filters_v2"
    const val TYPE_ASK_DOUBT_CARD = "ask_doubt_card"
    const val TYPE_IMAGE_CARD = "image_card"
    const val TYPE_VIDEO_CARD = "sg_video_card"
    const val TYPE_FEED_BANNER = "feed_banner"
    const val TYPE_HOME_WORK = "homework_trigger"
    const val TYPE_HOME_WORK_LIST = "homework_list"
    const val TYPE_HOME_WORK_LIST_V2 = "course_homework"
    const val TYPE_TOP_OPTION = "widget_top_option"
    const val TYPE_INCOMPLETE_CHAPTER = "widget_incomplete_chapter"
    const val TYPE_WIDGET_COLLAPSED = "widget_collapsed"
    const val TYPE_WIDGET_PLAYLIST = "widget_playlist"
    const val TYPE_HOME_WORK_HORIZONTAL_LIST = "homework_horizontal_list"
    const val TYPE_WIDGET_AUTOPLAY = "widget_autoplay"
    const val TYPE_WIDGET_CHILD_AUTOPLAY = "widget_child_autoplay"
    const val TYPE_WIDGET_UPCOMING_LIVE_CLASS = "widget_upcoming_live_class"
    const val TYPE_GRADIENT_CARD = "gradient_card"
    const val TYPE_BOOK_PROGRESS = "book_progress"
    const val TYPE_WIDGET_PAID_COURSE = "widget_paid_course"
    const val TYPE_YOU_WERE_WATCHING = "you_were_watching"
    const val TYPE_VIDEO_BANNER_AUTOPLAY_CHILD = "video_banner_autoplay_child"
    const val TYPE_VIDEO_AUTOPLAY_CHILD2 = "video_autoplay_child2"
    const val TYPE_FEED_PINNED_VIDEO_AUTOPLAY_CHILD = "feed_pinned_autoplay_child"
    const val TYPE_IMAGE_CARD_GROUP = "image_card_group"
    const val TYPE_FOLLOW_WIDGET = "widget_follow"
    const val TYPE_COURSE_TESTIMONIAL = "course_testimonial"
    const val TYPE_FACULTY_LIST = "course_teachers"
    const val TYPE_COURSE_FAQS = "course_faqs"
    const val TYPE_COURSE_CONTENT_LIST = "course_timetable"
    const val TYPE_COURSE_INFO = "course_info_v1"
    const val TYPE_COURSE_FEATURE = "course_features"
    const val TYPE_COURSE_EMI_INFO = "course_emi_info_v1"
    const val TYPE_TOP_DOUBT_ANSWER_VIDEO = "top_doubt_answer_video"
    const val TYPE_TOP_DOUBT_ANSWER_AUDIO = "top_doubt_answer_audio"
    const val TYPE_TOP_DOUBT_ANSWER_IMAGE = "top_doubt_answer_text_image"
    const val TYPE_FAQ = "faq"
    const val TYPE_PENDING_PAYMENT = "pending_payment"
    const val TYPE_WIDGET_COURSE_PARENT = "widget_course_parent"
    const val TYPE_WIDGET_COURSE_CLASSES = "widget_course_classes"
    const val TYPE_WIDGET_COURSE_TEST = "widget_course_test"
    const val TYPE_ALL_CLASSES = "all_classes"
    const val TYPE_INCREASE_VALIDITY = "validity_widget"
    const val TYPE_STORIES = "stories"
    const val TYPE_COURSE_SUBJECT_POST_PURCHASE = "course_subject_v1"
    const val TYPE_COURSE_RESOURCE_POST_PURCHASE = "course_cards"
    const val TYPE_NOTES_FILTER2 = "notes_filter2"
    const val TYPE_WIDGET_COURSE_AUTOPLAY = "course_video"
    const val TYPE_SCHEDULE_V2 = "schedule_v2"
    const val TYPE_TRIAL_TIMER = "trial_timer"
    const val TYPE_WIDGET_TEST = "widget_test"
    const val TYPE_WIDGET_VIEW_ALL = "widget_view_all"
    const val TYPE_SCHEDULE_MONTH_FILTER = "schedule_month_filter"
    const val TYPE_AUTO_SCROLL_CARD_WIDGET = "auto_scroll_home_banner"

    // NCERT Video Page
    const val TYPE_WIDGET_COLLAPSE_EXPAND_MATH_VIEW = "widget_collapse_expand_math_view"
    const val TYPE_WIDGET_VIDEO_ACTIONS = "widget_video_actions"
    const val TYPE_WIDGET_PARENT_GRID_SELECTION = "widget_parent_grid_selection"
    const val TYPE_WIDGET_CHILD_GRID_SELECTION = "widget_child_grid_selection"
    const val TYPE_WIDGET_NCERT_SIMILAR = "widget_ncert_similar"
    const val TYPE_WIDGET_NCERT_BOOK = "widget_ncert_book"

    const val TYPE_ATTENDANCE = "widget_attendance"
    const val TYPE_WIDGET_SIMILAR = "widget_similar"

    const val TYPE_WIDGET_POPULAR_COURSE = "widget_popular_course"
    const val TYPE_WIDGET_ASK_DOUBT = "widget_ask_doubt"
    const val TYPE_WIDGET_STUDY_DOST = "widget_studydost"
    const val TYPE_TEXT_WIDGET = "text_widget"
    const val PURCHASED_COURSE_LIST_WIDGET = "purchased_course_list"

    const val TYPE_WIDGET_COUPON_BANNER = "widget_coupon_banner"

    const val TYPE_PDF_NOTES = "widget_pdf_notes"
    const val TYPE_DOUBT_FEED_DAILY_GOAL = "widget_doubt_feed_daily_goal"
    const val TYPE_TOPIC_BOOSTER = "widget_topic_booster"
    const val TYPE_FORMULA_SHEET = "widget_formula_sheet"
    const val TYPE_TOPIC_VIDEO = "widget_topic_video"
    const val TYPE_ASKED_QUESTION = "widget_asked_question"
    const val TYPE_DOUBT_FEED_START_PRACTICE_WIDGET = "widget_doubt_feed_start_practice"
    const val TYPE_TOPIC_BOOSTER_GAME_BANNER = "widget_topic_booster_game_banner"
    const val TYPE_KHELO_JEETO_BANNER = "widget_khelo_jeeto_banner"
    const val TYPE_MY_COURSE = "widget_my_courses"
    const val TYPE_PRE_PURCHASE_CALL_CARD = "widget_pre_purchase_call_card"
    const val TYPE_PRE_PURCHASE_CALL_CARD_V2 = "widget_pre_purchase_call_card_v2"

    //Study Dost
    const val TYPE_WIDGET_STUDY_GROUP_BANNER_IMAGE = "widget_study_dost_banner_image"

    const val TYPE_WIDGET_STUDY_GROUP_PARENT = "widget_study_group_parent"
    const val TYPE_WIDGET_STUDY_GROUP_REPORT_PARENT = "widget_study_group_report_parent"
    const val TYPE_WIDGET_STUDY_DOST_PARENT = "widget_study_dost_parent"
    const val TYPE_WIDGET_STUDY_GROUP_LIVE_CLASS = "widget_study_group_live_class"
    const val TYPE_WIDGET_AUDIO_PLAYER = "widget_audio_player"
    const val TYPE_WIDGET_STUDY_GROUP_GUIDELINE = "widget_study_group_guideline"
    const val TYPE_WIDGET_STUDY_GROUP_INVITATION = "widget_study_group_invitation"
    const val TYPE_WIDGET_STUDY_GROUP_JOINED_INFO = "widget_study_group_joined_info"
    const val TYPE_WIDGET_STUDY_GROUP_FEATURE_UNAVAILABLE = "widget_study_group_feature_unavailable"
    const val TYPE_WIDGET_PDF_VIEW = "widget_pdf_view"
    const val TYPE_WIDGET_MY_SACHET = "widget_my_sachet"
    const val TYPE_DOUBT_FEED_BANNER = "widget_doubt_feed_banner"
    const val TYPE_WIDGET_NUDGE = "widget_nudge"
    const val TYPE_WIDGET_NUDGE_POPUP = "widget_nudge_popup"
    const val TYPE_WIDGET_SG_GROUP_CHAT = "widget_sg_group_chat"
    const val WIDGET_JOIN_NEW_STUDYGROUP = "widget_join_new_studygroup"
    const val TYPE_WIDGET_SG_HOME = "widget_sg_home"
    const val TYPE_WIDGET_SG_INDIVIDUAL_CHAT = "widget_sg_individual_chat"
    const val TYPE_WIDGET_SG_REQUEST = "widget_sg_request"
    const val TYPE_WIDGET_SG_BLOCKED_MEMBER = "widget_sg_blocked_member"

    const val TYPE_WIDGET_DOUBT_P2P_HOME = "widget_doubt_p2p_home"
    const val TYPE_WIDGET_DOUBT_P2P = "widget_doubt_p2p"
    const val TYPE_WIDGET_DOUBT_P2P_ANIMATION = "widget_doubt_p2p_animation"
    const val TYPE_PACKAGE_DETAIL_V3 = "package_details_v3"
    const val TYPE_WIDGET_CLASS_BOARD_EXAM = "widget_class_board_exam"

    const val TYPE_WIDGET_LEADERBOARD_PERSONAL = "widget_leaderboard_personal"
    const val TYPE_WIDGET_LEADERBOARD_TAB = "widget_leaderboard_tabDetails"
    const val TYPE_WIDGET_LEADERBOARD_TOP_THREE = "widget_leaderboard_top_three"
    const val TYPE_WIDGET_LEADERBOARD = "widget_leaderboard"
    const val TYPE_WIDGET_PARENT_COURSE_RECOMMENDATION_INCOMING = "widget_parent_cr_incoming"
    const val TYPE_WIDGET_COURSE_RECOMMENDATION_MESSAGE = "widget_cr_message"
    const val TYPE_WIDGET_COURSE_RECOMMENDATION_RADIO_BUTTON = "widget_cr_que_radio_btn"
    const val TYPE_WIDGET_COURSE_RECOMMENDATION_SUBMITTED_ANSWER = "widget_cr_submitted_answer"
    const val TYPE_NOTES_WIDGET_V2 = "widget_notes_v2"
    const val TYPE_WIDGET_SAMPLE_QUESTION = "widget_sample_question"
    const val TYPE_WIDGET_COURSE_EXPLORE = "widget_course_explore"

    const val TYPE_DOUBT_FEED = "widget_doubt_feed"
    const val TYPE_WIDGET_SYLLABUS = "widget_syllabus"
    const val TYPE_WIDGET_COURSE_INFO_WIDGET_2 = "widget_course_info_widget_2"
    const val TYPE_WIDGET_COURSE_DETAILS = "widget_course_details"
    const val TYPE_WIDGET_TRIAL_BUTTON = "widget_trial_button"
    const val TYPE_COURSE_TIME_TABLE = "widget_course_time_table"
    const val TYPE_COURSE_PLAN = "widget_course_plan"
    const val TYPE_WIDGET_COURSE_TEST_V2 = "widget_course_test_v2"
    const val TYPE_NOTES_LIST_V2 = "resource_notes_v2"
    const val TYPE_PACKAGE_DETAIL_V4 = "package_details_v4"
    const val TYPE_WIDGET_BUY_COMPLETE_COURSE = "widget_buy_complete_course"
    const val TYPE_WIDGET_VIEW_PLAN_BUTTON = "widget_view_plan_button"
    const val TYPE_WIDGET_BUTTON_BORDER = "widget_button_border"
    const val TYPE_WIDGET_SELECT_MEDIUM = "widget_select_medium"
    const val TYPE_WIDGET_CONTENT_FILTER = "widget_content_filter"
    const val TYPE_COURSE_INFO_V2 = "widget_course_info_v2"
    const val TYPE_TESTIMONIAL_V2 = "testimonial_v2"
    const val TYPE_COURSE_V4 = "widget_course_v4"
    const val TYPE_COURSE_V3 = "widget_course_v3"
    const val TYPE_COUPON_LIST = "widget_coupon_list"
    const val TYPE_COURSE_RESOURCE_V2 = "widget_course_resource_v2"

    const val TYPE_MEDIUM_SWITCH_WIDGET = "widget_medium_switch"
    const val TYPE_CALLING_NOTICE_WIDGET = "course_calling_widget"

    const val TYPE_EXAM_CORNER_DEFAULT_WIDGET = "exam_corner_default"
    const val TYPE_EXAM_CORNER_POPULAR_WIDGET = "exam_corner_popular"
    const val TYPE_EXAM_CORNER_AUTOPLAY_WIDGET = "exam_corner_autoplay"

    const val TYPE_WIDGET_TOP_SELLING_SUBJECT = "widget_top_selling_subject"
    const val TYPE_WIDGET_CALLING_BIG_CARD = "widget_calling_big_card"
    const val TYPE_WIDGET_COURSE_RECOMMENDATION = "widget_course_recommendation"
    const val TYPE_WIDGET_CATEGORY = "widget_category"
    const val TYPE_WIDGET_RECOMMENDED_TEST = "widget_recommended_test"
    const val TYPE_WIDGET_COURSE_INFO_V3 = "widget_course_wallet"
    const val TYPE_EXPLORE_PROMO_WIDGET = "widget_explore_promo"
    const val TYPE_VIDEO_WIDGET = "widget_video"
    const val TYPE_RECOMMENDATION_WIDGET = "widget_recommendation"
    const val TYPE_WIDGET_VPA = "widget_vpa"
    const val TYPE_TEST_ANALYSIS = "widget_test_analysis"
    const val TYPE_TEST_RESULT = "widget_mock_test_result"
    const val TYPE_REVISION_CORNER_BANNER = "widget_revision_corner_banner"
    const val TYPE_ICON_CTA = "widget_icon_cta"

    const val TYPE_LIVE_QUESTIONS_DAILY_PRACTICE_WIDGET = "widget_24x7"
    const val TYPE_LIVE_QUESTIONS_DAILY_PRACTICE_RANK_WIDGET = "widget_24x7_rank"
    const val TYPE_LIVE_QUESTIONS_DAILY_PRACTICE_FAQ_WIDGET = "widget_faq"
    const val TYPE_WIDGET_DAILY_PRACTICE = "widget_daily_practice"

    const val MY_REWARDS_POINTS_WIDGET = "my_rewards_points_widget"
    const val MY_REWARDS_SCRATCH_CARD_WIDGET = "my_rewards_scratch_card_widget"

    const val TYPE_BULLET_LIST_WIDGET = "bullet_list_widget"
    const val TYPE_PADHO_AUR_JEETO_WIDGET = "widget_padho_aur_jeeto"
    const val TYPE_LEADER_BOARD_PROGRESS = "widget_leader_board_progress"
    const val TYPE_AWARDED_STUDENTS_LIST = "widget_awarded_students_list"
    const val TYPE_REFERRAL = "widget_referral"
    const val TYPE_PREVIOUS_TEST_RESULTS = "widget_previous_test_results"
    const val TYPE_PRACTICE_TEST = "widget_practice_test"
    const val TYPE_SCHOLARSHIP_TABS = "widget_scholarship_tabs"
    const val TYPE_REPORT_CARD = "widget_report_card"
    const val TYPE_REGISTER_TEST = "widget_register_test"
    const val TYPE_PROGRESS = "widget_progress"
    const val TYPE_SCHOLARSHIP_PROGRESS_CARD = "widget_scholarship_progress_card"

    const val TYPE_TFS_ANALYSIS = "widget_tfs_analysis"
    const val TYPE_WIDGET_PARENT_TAB_2 = "widget_parent_tab2"
    const val TYPE_WIDGET_PARENT_TAB_3 = "widget_parent_tab3"

    const val TYPE_EXPLORE_COURSE_V2_SQUARE = "widget_explore_course_v2_square"
    const val TYPE_EXPLORE_COURSE_V2_CIRCLE = "widget_explore_course_v2_circle"
    const val TYPE_LATEST_LAUNCHES = "widget_latest_launches"

    const val TYPE_TEACHER_HEADER = "teacher_header"
    const val TYPE_ANNOUNCEMENT_WIDGET = "announcement_widget"
    const val TYPE_CHANNEL_FILTER = "filter_sub_tab"
    const val TYPE_CHANNEL_FILTER_TAB = "channel_filter_tabs"
    const val TYPE_CHANNEL_FILTER_CONTENT = "filter_content"
    const val TYPE_VIDEO_TYPE = "channel_video_content"
    const val TYPE_PDF_TYPE = "channel_pdf_content"

    const val TYPE_SUBSCRIBED_TEACHERS = "subscribed_teacher_channels"
    const val TYPE_TEACHERS_LIST = "teacher_channel_list"
    const val TYPE_WIDGET_TEACHER_CHANNEL_2 = "widget_teacher_channel_2"

    const val TYPE_WIDGET_DUMMY = "widget_dummy"
    const val TYPE_WIDGET_EXPLORE_CARD = "widget_explore_card"
    const val TYPE_WIDGET_FAVOURITE_EXPLORE_CARD = "widget_favourite_explore_card"
    const val TYPE_WIDGET_CHANNEL = "widget_channel"
    const val TYPE_WIDGET_VIDEO_OFFSET = "course_lecture_offsets"
    const val TYPE_WIDGET_MATCH_PAGE = "widget_match_page"

    //Doubtnut Rupya Widgets Start
    const val TYPE_WIDGET_DNR_EARNED_HISTORY = "widget_dnr_earned_history"
    const val TYPE_WIDGET_DNR_EARNED_HISTORY_ITEM = "widget_dnr_earned_history_item"
    const val TYPE_WIDGET_DNR_EARNED_SUMMARY = "widget_dnr_earned_history_summary"
    const val TYPE_WIDGET_DNR_UNLOCKED_VOUCHER = "widget_dnr_unlocked_voucher"
    const val TYPE_WIDGET_DNR_STREAK = "widget_dnr_streak"
    const val TYPE_WIDGET_DNR_TEXT = "widget_dnr_text_widget"
    const val TYPE_WIDGET_DNR_NO_EARNED_HISTORY = "widget_dnr_no_earned_history"
    const val TYPE_WIDGET_DNR_TOTAL_REWARD = "widget_dnr_total_reward"
    const val TYPE_WIDGET_DNR_EARNING_DETAILS = "widget_dnr_earning_detail"
    const val TYPE_WIDGET_DNR_REWARD_DETAIL = "widget_dnr_reward_detail"
    const val TYPE_WIDGET_DNR_REDEEM_VOUCHER = "widget_dnr_redeem_voucher"
    const val TYPE_WIDGET_DNR_TODAY_REWARD = "widget_dnr_today_reward"
    const val TYPE_WIDGET_DNR_REWARD_HISTORY = "widget_dnr_reward_history"
    const val TYPE_WIDGET_DNR_HOME = "widget_dnr_home"
    const val TYPE_WIDGET_LIBRARY_CARD = "widget_library_card"
    const val TYPE_WIDGET_LIBRARY_EXAM = "widget_library_exam"
    // Doubtnut Rupya Widgets End

    const val TYPE_WIDGET_EXPLORE_MORE = "widget_explore_more"

    const val TYPE_CHECKOUT_V2_HEADER = "widget_checkout_header"
    const val TYPE_CHECKOUT_V2_COUPON = "widget_checkout_coupon"
    const val TYPE_CHECKOUT_V2_CHILD = "widget_checkout_payment_method"
    const val TYPE_CHECKOUT_V2_PARENT = "widget_parent_checkout"
    const val TYPE_CHECKOUT_V2_WALLET = "widget_checkout_wallet"
    const val TYPE_CHECKOUT_V2_TALK_TO_US = "widget_checkout_talk_to_us"

    const val TYPE_WIDGET_TOP_SUBJECT_STUDYING = "widget_top_topics"
    const val TYPE_WIDGET_CLASSES_BY_TEACHER = "widget_classes_by_teacher"
    const val TYPE_YOU_WERE_WATCHING_V2 = "you_were_watching_v2"
    const val TYPE_WIDGET_CHAPTER_BY_CLASSES = "widget_chapter_by_classes"

    const val TYPE_COURSE_TIME_TABLE_V2 = "widget_course_time_table_v2"
    const val TYPE_WIDGET_MOST_VIEWED_CLASSES = "widget_most_viewed_classes"
    const val TYPE_WIDGET_FILTER_BUTTON = "filter_button"
    const val TYPE_WIDGET_FILTER_DROPDOWN = "widget_filter_dropdown"
    const val TYPE_WIDGET_MULTISELECT_SUBJECT_FILTER = "widget_multi_select_filter"

    const val TYPE_PREVIOUS_WINNERS_WIDGET = "previous_winners_widget"
    const val TYPE_WINNERS_CARD_WIDGET = "winners_card_widget"
    const val TYPE_WIDGET_COPY_TEXT = "widget_copy_text"
    const val TYPE_WIDGET_PRACTICE_ENGLISH = "widget_practice_english"

    const val TYPE_WIDGET_SRP_NUDGE = "widget_srp_nudge"
    const val TYPE_WIDGET_SUBJECT_COURSE_CARD = "widget_subject_course_card"

    //free_trial_course
    const val TYPE_FREE_TRIAL_COURSE="widget_trial_course"
    const val TYPE_GRADIENT_CARD_WITH_BUTTON="widget_gradient_card"
    const val TYPE_WIDGET_COURSE_CAROUSEL = "live_class_carousel_card_3"
    const val NEXT_SCREEN_WIDGET = "next_screen_widget"
    const val ENGLISH_QUIZ_INFO_WIDGET = "english_quiz_info_widget"
    const val INVITE_FRIEND_WIDGET = "widget_share"

    const val TYPE_REFERRAL_STEPS_WIDGET = "referral_steps"
    const val TYPE_REFERRAL_LEVEL_WIDGET = "referral_level_widget"
    const val TYPE_IMAGE_TEXT_WIDGET = "referral_goodie_widget"
    const val TYPE_REFERRAL_WINNER_EARN_MORE_WIDGET = "referral_winner_earn_more_widget"
    const val TYPE_REFERRAL_WINNER_CONGRATULATIONS_WIDGET = "referral_winner_congratulation_widget"
    const val TYPE_REFERRAL_WINNER_EARN_MORE_WIDGET_V2 = "referral_winner_earn_more_widget_v2"
    const val TYPE_REFERRAL_VIDEO_WIDGET = "referral_video_widget"
    const val TYPE_REFERRAL_CLAIM_WIDGET = "referral_claim_widget"
    const val TYPE_MATCH_PAGE_EXTRA_FEATURE = "widget_match_page_extra_feature"


    const val TYPE_REFER_AND_EARN_HEADER_WIDGET="widget_refer_and_earn_header"
    const val TYPE_REFER_AND_EARN_STEPS_WIDGET="widget_refer_and_earn_steps_widget"
    const val TYPE_REFERRAL_CODE_WIDGET="widget_referral_code"
    const val TYPE_REFERRED_FRIENDS_WIDGET="widget_referred_friends"

    const val TYPE_WIDGET_SHORTS_VIDEO_DEFAULT = "widget_shorts_video_default"
    const val TYPE_SHORTS_VIDEOS_EXHAUSTED_WIDGET = "widgets_shorts_videos_exhausted"
    const val TYPE_WIDGET_SHORTS_VIDEO_PROGRESS = "widget_shorts_video_progress"

    const val TYPE_WIDGET_NO_DATA = "widget_no_data"
    const val TYPE_WIDGET_FILTER_SORT = "widget_filter_sort"
    const val TYPE_WIDGET_TWO_TEXTS_HORIZONTAL = "widget_two_texts_horizontal"
    const val TYPE_WIDGET_WATCH_AND_WIN = "widget_watch_and_win"
    const val TYPE_WIDGETS_TWO_TEXTS_VERTICAL_TABS = "widgets_two_texts_vertical_tabs"
    const val TYPE_WIDGET_WATCH_NOW = "widget_watch_now"

    const val GRADIENT_CARD_WITH_CTA="gradient_card_with_cta"

    const val TYPE_WIDGET_IAS = "widget_ias"
    const val TYPE_WIDGET_RC_TEST_PAPER = "widget_rc_test_paper"
    const val TYPE_WIDGET_RC_PREVIOUS_YEAR_PAPER = "widget_rc_previous_year_paper"
    const val TYPE_VERTICAL_PARENT_WIDGET = "widget_vertical_parent"

    const val TYPE_D0_QA_WIDGET = "widget_d0_qa"

    const val TYPE_COUPON_APPLIED_WIDGET = "widget_coupon_applied"
    const val TYPE_CLIPBOARD_WIDGET = "widget_clipboard"

    const val TYPE_TIMER_WIDGET = "widget_timer"

    const val TYPE_DOUBT_PE_CHARCHA_QUESTION="widget_doubt_pe_charcha_question"
    const val TYPE_GRADIENT_BANNER_WITH_ACTION_BUTTON_WIDGET="widget_gradient_banner_with_action_button"
    const val TYPE_BADGE_FOR_LEVEL="type_badge_for_level"
    const val TYPE_USER_BADGE_BANNER_WIDGET="widget_user_badge_banner"
    const val TYPE_DOUBT_SUGGESTER_WIDGET = "widget_doubt_suggester"

    // Result Page Widgets Start
    const val TYPE_MORE_TESTIMONIALS_WIDGET = "widget_more_testimonials"
    const val TYPE_TOPPERS_WIDGET = "widget_toppers"
    const val TYPE_EXCEL_COURSES_WIDGET = "widget_excel_courses_widget"

}